[2023-07-28 11:26:32,486]: INFO: main: Welcome to my custom log
[2023-07-28 13:42:20,972]: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<
[2023-07-28 13:42:20,972]: ERROR: main: [Errno 2] No such file or directory: 'config/config.yaml'
[2023-07-28 17:38:27,102]: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<
[2023-07-28 17:38:27,102]: ERROR: main: [Errno 2] No such file or directory: 'config/config.yaml'
Traceback (most recent call last):
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/templates/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/config/configuration.py", line 19, in __init__
    self.config = read_yaml(config_filepath)
  File "/Users/gardy/miniforge3/envs/cnncls/lib/python3.9/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/utils/common.py", line 37, in read_yaml
    raise e
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/utils/common.py", line 30, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2023-07-28 17:39:01,039]: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<
[2023-07-28 17:39:01,039]: ERROR: main: [Errno 2] No such file or directory: 'config/config.yaml'
Traceback (most recent call last):
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/templates/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/config/configuration.py", line 19, in __init__
    self.config = read_yaml(config_filepath)
  File "/Users/gardy/miniforge3/envs/cnncls/lib/python3.9/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/utils/common.py", line 37, in read_yaml
    raise e
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/utils/common.py", line 30, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2023-07-28 17:47:17,698]: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<
[2023-07-28 17:47:17,698]: ERROR: main: [Errno 2] No such file or directory: 'config/config.yaml'
Traceback (most recent call last):
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/templates/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/config/configuration.py", line 19, in __init__
    self.config = read_yaml(config_filepath)
  File "/Users/gardy/miniforge3/envs/cnncls/lib/python3.9/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/utils/common.py", line 37, in read_yaml
    raise e
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/utils/common.py", line 30, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2023-07-28 17:47:29,039]: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<
[2023-07-28 17:47:29,039]: ERROR: main: [Errno 2] No such file or directory: 'config/config.yaml'
Traceback (most recent call last):
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/templates/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/config/configuration.py", line 19, in __init__
    self.config = read_yaml(config_filepath)
  File "/Users/gardy/miniforge3/envs/cnncls/lib/python3.9/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/utils/common.py", line 37, in read_yaml
    raise e
  File "/Users/gardy/Desktop/Recent/Machine_learning_projects/Krishnaik/MLOps_entire_project/My_Implementation/src/cnnClassifier/utils/common.py", line 30, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2023-07-28 17:48:02,748]: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<
[2023-07-28 17:48:02,750]: INFO: common: yaml file: config/config.yaml loaded successfully
[2023-07-28 17:48:02,750]: INFO: common: yaml file: params.yaml loaded successfully
[2023-07-28 17:48:02,750]: INFO: common: created directory at: artifacts
[2023-07-28 17:48:02,750]: INFO: common: created directory at: artifacts/data_ingestion
[2023-07-28 17:48:06,701]: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: F2E6:EB4A:C3388C:CA5ED7:64C3E333
Accept-Ranges: bytes
Date: Fri, 28 Jul 2023 15:48:03 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpg1960077-PAR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1690559283.161731,VS0,VE489
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 972b3c65f24a5a8d7c415d3295ab81404123c4a1
Expires: Fri, 28 Jul 2023 15:53:03 GMT
Source-Age: 0


[2023-07-28 17:48:06,787]: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2023-07-28 17:48:06,787]: INFO: main: *******************
[2023-07-28 17:48:06,787]: INFO: main: >>>>>> stage Prepare base model started <<<<<<
[2023-07-28 17:48:06,788]: INFO: common: yaml file: config/config.yaml loaded successfully
[2023-07-28 17:48:06,789]: INFO: common: yaml file: params.yaml loaded successfully
[2023-07-28 17:48:06,789]: INFO: common: created directory at: artifacts
[2023-07-28 17:48:06,789]: INFO: common: created directory at: artifacts/prepare_base_model
[2023-07-28 17:48:06,986]: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2023-07-28 17:48:07,035]: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.
[2023-07-28 17:48:07,038]: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.
[2023-07-28 17:48:07,067]: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2023-07-28 17:49:12,254]: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<
[2023-07-28 17:49:12,256]: INFO: common: yaml file: config/config.yaml loaded successfully
[2023-07-28 17:49:12,256]: INFO: common: yaml file: params.yaml loaded successfully
[2023-07-28 17:49:12,256]: INFO: common: created directory at: artifacts
[2023-07-28 17:49:12,257]: INFO: common: created directory at: artifacts/data_ingestion
[2023-07-28 17:49:16,441]: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: F2E6:EB4A:C3388C:CA5ED7:64C3E333
Accept-Ranges: bytes
Date: Fri, 28 Jul 2023 15:49:12 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpg1960074-PAR
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1690559353.523009,VS0,VE2
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 7244994a8124768f5475df82932d6442106b5b11
Expires: Fri, 28 Jul 2023 15:54:12 GMT
Source-Age: 69


[2023-07-28 17:49:16,527]: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2023-07-28 17:49:16,527]: INFO: main: *******************
[2023-07-28 17:49:16,527]: INFO: main: >>>>>> stage Prepare base model started <<<<<<
[2023-07-28 17:49:16,528]: INFO: common: yaml file: config/config.yaml loaded successfully
[2023-07-28 17:49:16,529]: INFO: common: yaml file: params.yaml loaded successfully
[2023-07-28 17:49:16,529]: INFO: common: created directory at: artifacts
[2023-07-28 17:49:16,529]: INFO: common: created directory at: artifacts/prepare_base_model
[2023-07-28 17:49:16,728]: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2023-07-28 17:49:16,771]: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.
[2023-07-28 17:49:16,774]: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.
[2023-07-28 17:49:16,804]: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x
